### ISSUE TITLE
Add list of programs currently supported in docs

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCEngine#146]
QCEngine supports executing a variety of quantum chemistry, semiempirical, and molecular mechanics programs. The programs currently supported appear to be:

```python
> from qcengine import list_all_programs
> list_all_programs()
{'dftd3',
 'entos',
 'molpro',
 'mopac',
 'mp2d',
 'psi4',
 'rdkit',
 'terachem',
 'torchani'}
```
The docs do not currently indicate what QCEngine supports. I propose we add a docs page with the list of currently-supported programs, possibly with comments as to what is and is not supported for each.

**Comment by dotsdl** [comment]
I'm happy to build a stub for this if desired. I don't have enough insight yet to fill in the meat for each program harness (as to what the limits of support are), but have some things I've built that fit the bill structurally.

**Comment by loriab** [comment]
The meat is harder to define than it ought to be, partially because many people are writing the interfaces and because, in scope, QCEngine should run any QCSchemus, and 99.5% of any program's capability should be definable by QCSchema.

Ideally, I'd like the tests to scrape program, method, driver, and maybe frozen-core & reference and build its own capabilities list that autoupdates.

Practically, I think two sentences in the docs somewhere with an overview of what's known to work and not work will serve good purpose and keep everyone away from rabbit holes. If you've a stub in mind, I'm all for it.

**Comment by dgasmith** [comment]
A simple checklist should be good enough. Energy/gradient/Hessian/properties/Wavefunction would cover a pretty high level overview.

**Comment by sjrl** [comment]
In this checklist should we specifically say which methods of the target program are supported? And do we document that each program will have it's own set of keywords?

**Comment by mattwelborn** [comment]
I envision that we could have a grid with programs as rows and "energy", "gradient", "Hessian", "properties", "wavefunction" as columns. Each cell would be one of Full support, no support, or partial support. Details about exactly what is available can live in the docs.

**Comment by mattwelborn** [comment]
We have this now: http://docs.qcarchive.molssi.org/projects/QCEngine/en/stable/program_overview.html. Let us all endeavor to actually keep it up to date...
