### ISSUE TITLE
Turbomole support

### ISSUE THREAD

**Issue by eljost** [MolSSI/QCEngine#157]
Hi,
a request for a TURBOMOLE interface came up in this [geomeTRIC issue](https://github.com/leeping/geomeTRIC/issues/97).
As I already developed a TM-wrapper for my own [code](https://github.com/eljost/pysisyphus/tree/dev) I'd be willing to work on an implementation in QCEngine.
Right now the way my wrapper works is quite incompatible to QCEngine I imagine... In my code you have to prepare a control-file beforehand (through the TM-utility `define`) that gets passed to the wrapper class. All contents from this directory get copied to a temporary directory, from where the calculation is actually run.

What is needed for QCEngine is probably a wrapper for `define`?!
What would you consider to the minimal feature-set that should be implemented?

Best regards
Johannes

**Comment by dgasmith** [comment]
TURBOMOLE integration would be fantastic and something that has been asked after before.

A minimal viable block for a compute is a SCF energy/gradient return. This would satisfy the `geomeTRIC` requirements as well. A lot of the technology behind your wrapper can be reused I believe. The first step would be to join Slack (on the README of this repo) so that we can chat a bit about possible solutions and integrations. If TURBOMOLE does not support some sort of binary output it would like be the case that the wrapper would look similar to [NWChem](https://github.com/MolSSI/QCEngine/blob/master/qcengine/programs/nwchem/runner.py).

Overall QCEngine would like to support projects like `pysisyphus` so that everyone does not have to rewrite these wrappers. We look forward to working with you on this.

**Comment by mkrompiec** [comment]
@eljost: great that you are happy to do this. I think a wrapper for define would be a good idea, as long as examples of "typical" use cases are given. One more thing: pysiphus is released under GPL, would you  be happy to release the code under a more permissive license?

**Comment by dgasmith** [comment]
@mkrompiec I believe the Turbomole wrapper is now in here under BSD-3C.

Thanks again @eljost for this! We look forward to running Turbomole :)
