### ISSUE TITLE
Geometry Optimization within QC Codes

### ISSUE THREAD

**Issue by WardLT** [MolSSI/QCEngine#197]
**Is your feature request related to a problem? Please describe.**
I would like to use the optimizers baked in to QC codes to perform geometry optimizations. My concern that using geoMETRIC could be especially inefficient with MPI codes as it will call `mpiexec` very frequently.

**Describe the solution you'd like**
A Procedure that calls the geometry optimization for NWChem. 

**Describe alternatives you've considered**
- Adding a driver for geometry optimizations. However, the `compute` drivers seems to all not effect geometry
- Modifying geoMETRIC/qcengine to preserve NWChem output files so it can read in restart files. I think this might be a better option than the "solution I'd like" as it could work with any code that writes restart files and allows me to use geoMETRIC's optimizer.

**Additional context**
I've got time to work on this, just need some direction :)

**Comment by dgasmith** [comment]
Great, this is not exactly an uncommon request :). I think a `ProcedureHarness` is the way forward here where this harness would inherit from the `NWChemHarness`. The main caveat here is that the `program` in the `ProcedureHarness` could only be NWChem. So you have this inner/outer program specification which must be the same.

You should be able to share a great deal of infrastructure, but the output parsing will be a bit different.

I think we would want to refactor the Harness a bit to be a general construct rather than a program/procedure specific one as well. So some thought would need to go into here.

As a note this should be thought about in a general manner of "my foundational program can do many things, how do I box its capabilities where the QCArchive architecture views it as separate pieces".

@Lnaden @sjayellis @mattwelborn @loriab might want to comment here as well.

**Comment by mattwelborn** [comment]
Is this a problem that MDI could solve?

**Comment by loriab** [comment]
A few thoughts:

* Last time I broached using NWChem optimizer in a standalone (aka restart) mode with TLW, she wasn't optimistic.
* I definitely support ProcedureHarness for this. Even if can't inherit from the `NWChemHarness`, should be able to expand the parsing infrastructure to support handling optimizations. So, `parse_output` can call functions from the programharness.
* As half a model, the Cfour harness breaks up instantiation outputs into optimization passes, then applies a normal AtomicResult parsing to each. Cfour internal optimizer not fit for Procedure treatment, though, because it needs internal coordinates as input, and that's not in `models.Molecule`.
* The "my foundational program can do many things, how do I box its capabilities where the QCArchive architecture views it as separate pieces" extensions where programs can be tricked (i.e., native files imitated) into broader input sources is smaller than you might expect since QC codes are so tightly coupled. But the simpler nwchem@nwchem setup proposed here is more feasible and will likely be informative. Personally, I like the nwchem optimizer!
* These must be mighty short gradient calcs to be worried they'll be dwarfed by startup costs?
* I hope nwc has an opt history file that can be dragged along.

**Comment by dgasmith** [comment]
@mattwelborn @taylor-a-barnes I think that this is problem that MDI will solve in the future (performance). But we also need to consider specific algorithms in NWChem (STEPPER) and Gaussian that do not have OSS driver counterparts. As noted QC programs are often very tightly coupled and difficult to pry apart in the manner that we wish, so this is more of a question of what do we need in the next month?

**Comment by WardLT** [comment]
I'll try to make a ProcedureHarness for the NWChem optimizer, since that seems to be a simpler route forward and let you know if I see much of an improvement over geoMETRIC+QCEngine

**Comment by dgasmith** [comment]
Great! Ping us if you have any issues. I think one item to note is that we may not be able to parse all intermediate gradients easily.

**Comment by WardLT** [comment]
I made a procedure harness for NWChem's relaxation awhile back: #281
