### ISSUE TITLE
mopac test refs

### ISSUE THREAD

**Issue by loriab** [MolSSI/QCEngine#373]
Hi @godotalgorithm, I hear you're the MolSSI consult on Mopac. When you get a chance, please take a look at the changes to test refs in #372 . I wouldn't be surprised if those tests hadn't been run regularly since 2019. I'm comfortable enough with the changes to include in release, but I wanted to keep you in the loop. Thanks.

**Comment by godotalgorithm** [comment]
Yeah, I saw that earlier today, I wasn't clear on how quickly you wanted a response. The relevant change in the change log is just switching to the conda-forge version of MOPAC, which is mostly up to date right now and something that I'll be actively maintaining in the future (I am already on the maintainer list). Is anything MOPAC-related being tested here other than installing it from conda-forge? Also, what was the source of a MOPAC executable prior to this change, or are the tests otherwise insensitive to the presence/absence of MOPAC and/or assume it is installed independently?
